[package]
name = "calgae-core"
version = "0.1.0"
edition = "2024"

resolver = "2"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
once_cell = "1.19"

tokio = { version = "1", features = ["full"] }
anyhow = "1.0"

candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-transformers = "0.9.1"
hf-hub = "0.4.3"
tokenizers = "0.22.1"

half = { version = "2.6.0", default-features = false }
rand_distr = { version = "0.5.1", default-features = false }

thiserror = "2.0.16"
serde_json = "1.0.145"
serde = { version = "1.0", features = ["derive"] }

pyo3 = { version = "0.26.0", features = ["abi3-py38"] }

rand = "0.9.2"
futures = "0.3"

[build-dependencies]
hf-hub = "0.4.3"
[[bin]]
name = "xtask"
path = "src/bin/xtask.rs"
