[package]
name = "calgae"
version = "0.1.0"
edition = "2021"

resolver = "2"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
once_cell = "1.19"

tokio = { version = "1", features = ["full"] }
anyhow = "1.0"

# Candle for lightweight inference on safetensors weights
candle-core = "0.7.0"
candle-nn = "0.7.0"
candle-transformers = "0.7.0"
hf-hub = "0.4.3"
tokenizers = "0.19.1"

num_cpus = "1.16"
half = "2.3.1"

rand_distr = "0.4.3"

thiserror = "2.0.16"

log = "0.4"

serde_json = "1.0.145"

serde = { version = "1.0", features = ["derive"] }

rand = "0.8.5"
futures = "0.3"
tempfile = "3.10"

[build-dependencies]
cc = { version = "1.1", features = ["parallel"] }
hf-hub = "0.4.3"
[[bin]]
name = "xtask"
path = "src/bin/xtask.rs"

[[bin]]
name = "calgae"
path = "src/main.rs"
