[package]
name = "calgae-core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
once_cell = "1.19"

[build-dependencies]
cc = "1.0"
cmake = "0.1"
bindgen = "0.69"
